// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ldap} from '../models';
import {update} from '../models';
import {sysenv} from '../models';
import {adtypes} from '../models';
import {m365} from '../models';
import {main} from '../models';

export function AccurateLastLogon(arg1:string):Promise<ldap.LastLogonReport>;

export function AppVersion():Promise<string>;

export function CheckForUpdate():Promise<update.Available>;

export function ClearCache():Promise<void>;

export function Connect(arg1:ldap.ConnectOptions):Promise<ldap.ServerInfo>;

export function DeleteSecret(arg1:string):Promise<void>;

export function DetectDomain():Promise<sysenv.Domain>;

export function Disconnect():Promise<void>;

export function GetACL(arg1:string):Promise<adtypes.SecurityDescriptor>;

export function GetSecret(arg1:string):Promise<string>;

export function HasSecret(arg1:string):Promise<boolean>;

export function InstallUpdate(arg1:string,arg2:string):Promise<void>;

export function IsConnected():Promise<boolean>;

export function M365Account():Promise<string>;

export function M365Check(arg1:Array<string>,arg2:boolean):Promise<Array<m365.User>>;

export function M365LicenseReport():Promise<Array<m365.LicenseSku>>;

export function M365PollSignIn():Promise<boolean>;

export function M365SignInInteractive(arg1:string,arg2:string):Promise<void>;

export function M365SignOut():Promise<void>;

export function M365SignedIn():Promise<boolean>;

export function M365StartSignIn(arg1:string,arg2:string):Promise<m365.DeviceCode>;

export function SchemaAttributes():Promise<Array<string>>;

export function Search(arg1:ldap.SearchRequest):Promise<ldap.SearchResult>;

export function SearchCached(arg1:ldap.SearchRequest,arg2:boolean):Promise<main.CachedSearch>;

export function ServerInfo():Promise<ldap.ServerInfo>;

export function StoreSecret(arg1:string,arg2:string):Promise<void>;
