// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccurateLastLogon(arg1) {
  return window['go']['main']['App']['AccurateLastLogon'](arg1);
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteSecret(arg1) {
  return window['go']['main']['App']['DeleteSecret'](arg1);
}

export function DetectDomain() {
  return window['go']['main']['App']['DetectDomain']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetACL(arg1) {
  return window['go']['main']['App']['GetACL'](arg1);
}

export function GetSecret(arg1) {
  return window['go']['main']['App']['GetSecret'](arg1);
}

export function HasSecret(arg1) {
  return window['go']['main']['App']['HasSecret'](arg1);
}

export function InstallUpdate(arg1, arg2) {
  return window['go']['main']['App']['InstallUpdate'](arg1, arg2);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function M365Account() {
  return window['go']['main']['App']['M365Account']();
}

export function M365Check(arg1, arg2) {
  return window['go']['main']['App']['M365Check'](arg1, arg2);
}

export function M365LicenseReport() {
  return window['go']['main']['App']['M365LicenseReport']();
}

export function M365PollSignIn() {
  return window['go']['main']['App']['M365PollSignIn']();
}

export function M365SignInInteractive(arg1, arg2) {
  return window['go']['main']['App']['M365SignInInteractive'](arg1, arg2);
}

export function M365SignOut() {
  return window['go']['main']['App']['M365SignOut']();
}

export function M365SignedIn() {
  return window['go']['main']['App']['M365SignedIn']();
}

export function M365StartSignIn(arg1, arg2) {
  return window['go']['main']['App']['M365StartSignIn'](arg1, arg2);
}

export function SchemaAttributes() {
  return window['go']['main']['App']['SchemaAttributes']();
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SearchCached(arg1, arg2) {
  return window['go']['main']['App']['SearchCached'](arg1, arg2);
}

export function ServerInfo() {
  return window['go']['main']['App']['ServerInfo']();
}

export function StoreSecret(arg1, arg2) {
  return window['go']['main']['App']['StoreSecret'](arg1, arg2);
}
